project:
  name: Skye Trading bot
  serviceName: Skye-trading-bot
  timezone: Asia/Novosibirsk

telegram:
  token:  <YOUR_BOT_TOKEN>

# Настройки базы данных MySQL
database:
  host: mysql
  port: 3306
  database_name: db_name
  username: my_app_user
  password: my_app_password


# настройки для отправки логов
telemetry:
  graylogPath: 127.0.0.1:12201


# Настройки внешнего API для загрузки номенклатуры
product_api:
  kind: "resto_api"
  base_url: https://resto.evotor.tech/api/3rdparty
  auth:  <YOUR_API_TOKEN>
  store:  <YOUR_STORE_UUID>

# Настройки внешнего API для создания заказов
order_api:
  kind: "resto_api"
  base_url: https://resto.evotor.tech/api/3rdparty
  auth:  <YOUR_API_TOKEN>
  store: <YOUR_API_TOKEN>
